

package org.jetbrains.kotlin.compiler.plugin.template.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.compiler.plugin.template.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    runTest("compiler-plugin/testData/diagnostics/simple.kt");
  }

  @Test
  @TestMetadata("simpleMutableTest.kt")
  public void testSimpleMutableTest() {
    runTest("compiler-plugin/testData/diagnostics/simpleMutableTest.kt");
  }

  @Test
  @TestMetadata("simpleUnitTest.kt")
  public void testSimpleUnitTest() {
    runTest("compiler-plugin/testData/diagnostics/simpleUnitTest.kt");
  }

  @Test
  @TestMetadata("simpleVarCheck.kt")
  public void testSimpleVarCheck() {
    runTest("compiler-plugin/testData/diagnostics/simpleVarCheck.kt");
  }

  @Test
  @TestMetadata("unitExpressionTest.kt")
  public void testUnitExpressionTest() {
    runTest("compiler-plugin/testData/diagnostics/unitExpressionTest.kt");
  }
}
